kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./build/Dockerfile
  context: .

spec:
  operator: jax
  image: image
  command: "python3 -u main.py --operator=jax --sleep=120 --tb-write=True"

  tensorboard:
    enabled: true

  types:
    Worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 1
        shmSizeGB: 0
        accelerators: # optional
          gpu:
            count: 1
            type: gpu
            product: t4

