name: demo

on:
  push: 
    branches: 'test-*'
    paths:
      - 'manifest.yaml'

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: echo "hello world"